Fix: Protect against "no Entry found" in EntryExpirationJob
Not sure how we get to this state, but production raised an exception
for a missing FleetTracker::Registry::Entry being queried against.

https://app.honeybadger.io/projects/129535/faults/117699722

```
NoMethodError: undefined method 'expired?' for nil

    return unless entry.expired?
                       ^^^^^^^^^
```