Update brakeman gem to fix CI failure
Because previously, the scan_ruby GitHub Action was failing with:

```
Run bin/brakeman --no-pager
Brakeman 6.2.2 is not the latest version 7.0.0
Error: Process completed with exit code 5.
```