Fix `psych` gem installation error on kamal deploy
Per Grok:
libyaml-dev provides the yaml library headers needed for psych.

Error was:

```
12.72 Bundler::Worker#create_threads'
12.72
12.72 An error occurred while installing psych (5.2.2), and Bundler cannot continue.
12.72
12.72 In Gemfile:
12.72   gemwork was resolved to 0.7.4, which depends on
12.72     debug was resolved to 1.10.0, which depends on
12.72       irb was resolved to 1.14.3, which depends on
12.72         rdoc was resolved to 6.10.0, which depends on
12.72           psych
------
Dockerfile:38
--------------------
  37 |     COPY Gemfile Gemfile.lock ./
  38 | >>> RUN bundle install && \
  39 | >>>     rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git
  40 |
--------------------
ERROR: failed to solve: process "/bin/sh -c bundle install &&     rm -rf ~/.bundle/ \"${BUNDLE_PATH}\"/ruby/*/cache \"${BUNDLE_PATH}\"/ruby/*/bundler/gems/*/.git" did not complete successfully: exit code: 5
```