Connect Games <-> Users via "through" associations
Examples:

```ruby
Game.last.cons.users # => [<User[..051c1ac9d439] :: Unknown User>]

User.last.cons.games # =>
[<Game[93](Intermediate / Sweep in Progress) 2024-09-13 01:28:16 -0500..>,
 <Game[92](Beginner / Mines Win) 2024-09-13 01:28:10 -0500..2024-09-13 01:28:10 -0500>,
 <Game[91](Expert / Mines Win) 2024-09-12 23:33:42 -0500..2024-09-12 23:33:43 -0500>,
 <Game[90](Beginner / Mines Win) 2024-09-12 23:31:52 -0500..2024-09-12 23:31:56 -0500>,
 <Game[89](Beginner / Alliance Wins) 2024-09-12 23:19:59 -0500..2024-09-12 23:20:21 -0500>,
 <Game[88](Beginner / Alliance Wins) 2024-09-12 23:17:22 -0500..2024-09-12 23:19:13 -0500>,
 <Game[87](Intermediate / Mines Win) 2024-09-12 23:16:46 -0500..2024-09-12 23:17:01 -0500>,
 <Game[86](Intermediate / Mines Win) 2024-09-12 23:15:17 -0500..2024-09-12 23:15:18 -0500>,
 <Game[85](Beginner / Mines Win) 2024-09-12 23:02:20 -0500..2024-09-12 23:02:23 -0500>,
 <Game[84](Beginner / Mines Win) 2024-09-12 23:00:13 -0500..2024-09-12 23:00:32 -0500>,
 <Game[83](Intermediate / Alliance Wins) 2024-09-12 21:41:29 -0500..2024-09-12 21:46:34 -0500>,
 <Game[82](Intermediate / Alliance Wins) 2024-09-11 16:43:40 -0500..2024-09-12 19:31:42 -0500>]
```

Note: The scope for the Game `has_many :users` association got funky
because PostgreSQL. Postgres requires that the `DISTINCT ON` / select
portion of the query matches the `order_by` portion. And I'm not sure
from there, but, without adding the custom `select()` specification, we
get:

```
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list (PG::InvalidColumnReference)
```

Also:
- Reorder the "through" associations between Game and Cell so that
  they're also useful outside of just for our `cell_*_transactions`
  associations as well.